### ISSUE TITLE
Running phate, no module named 's_gd2.swig._layout / $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by htejedam** [KrishnaswamyLab/phateR#68]
Hello, 
I managed to install phate in Windows just as indicated in the installation README, and I get an error when trying to run `phateR::phate(data)`
I tried then tried to install phate via Seurat, following: 
```
devtools::install_github("scottgigante/seurat", ref="patch/add-PHATE-again")
detach(package:Seurat, unload=TRUE)
```
But when running:
`Seurat::RunPHATE(data)`
I get the same result. I have also tried installing it on ubuntu, but when running I obtain similar error related to the s_gd2.swig._layout.

**Whole error in R reads**
```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe
Traceback (most recent call last):
  File "C:\Users\hteje\ANACON~1\envs\SCP_env\lib\site-packages\s_gd2\swig\layout.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\hteje\ANACON~1\envs\SCP_env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "C:\Users\hteje\AppData\Local\R\win-library\4.2\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "C:\Users\hteje\AppData\Local\R\win-library\4.2\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "C:\Users\hteje\AppData\Local\R\win-library\4.2\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 's_gd2.swig._layout'

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe
Error : ImportError: numpy.core.multiarray failed to import

Error in pyphate()$PHATE : $ operator is invalid for atomic vectors
```

**System information:**

Output of `phate.__version__`: '1.0.10'

Output of `sessionInfo()`:

<details>

```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_Netherlands.utf8  LC_CTYPE=English_Netherlands.utf8    LC_MONETARY=English_Netherlands.utf8
[4] LC_NUMERIC=C                         LC_TIME=English_Netherlands.utf8    

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] phateR_1.0.7           SCP_0.3.0              pheatmap_1.0.12        tibble_3.1.8           OmnipathR_3.6.0       
 [6] decoupleR_2.4.0        SoupX_1.6.2            readxl_1.4.1           webr_0.1.5             EnhancedVolcano_1.16.0
[11] ggrepel_0.9.3          enrichR_3.1            data.table_1.14.8      RColorBrewer_1.1-3     patchwork_1.1.2       
[16] DoubletFinder_2.0.3    ROCR_1.0-11            KernSmooth_2.23-20     fields_14.1            spam_2.9-1            
[21] ggsci_2.9              viridis_0.6.2          viridisLite_0.4.1      reticulate_1.28        umap_0.2.9.0          
[26] cowplot_1.1.1          Rsamtools_2.14.0       Biostrings_2.66.0      XVector_0.38.0         GenomicRanges_1.50.2  
[31] GenomeInfoDb_1.34.9    IRanges_2.32.0         S4Vectors_0.36.1       SeuratObject_4.1.3     Seurat_4.2.0.999      
[36] stringi_1.7.12         devtools_2.4.5         usethis_2.1.6          tidyr_1.3.0            glue_1.6.2            
[41] CellChat_1.5.0         Biobase_2.58.0         BiocGenerics_0.44.0    ggplot2_3.4.1          igraph_1.4.1          
[46] dplyr_1.1.0            Matrix_1.5-3    
```

Help would be highly appreciated. Thanks!

**Comment by htejedam** [comment]
I saw how to solve it.
`pip install scipy --upgrade`
`pip install numpy --upgrade`

As an extra note, you might get this error when working with large data sets

`Error: AttributeError: 'NoneType' object has no attribute 'split'`

You can solve it with
 `pip install -U threadpoolctl`

**Comment by AlexWeinreb** [comment]
In case you can't update due to version conflicts:

```
reticulate::virtualenv_create("phate")
reticulate::virtualenv_install("phate", "phate")
```

and before calling the function:
```
reticulate::use_virtualenv("phate")
res <- phate(data = ...)
```

**Comment by No2Ross** [comment]
Hi. I have exactly the same error occuring, but upgrading numpy and scipy does not fix it, neither does the virtualenv reticulate commands.

Python version 3.9.7

phate.__version__ = 1.0.11

sessionInfo()

R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] phateR_1.0.7    Matrix_1.5-1    reticulate_1.28

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10        plyr_1.8.8         cellranger_1.1.0   compiler_4.1.2     pillar_1.9.0       RColorBrewer_1.1-3 tools_4.1.2       
 [8] memoise_2.0.1      jsonlite_1.8.4     lifecycle_1.0.3    tibble_3.2.1       gtable_0.3.3       lattice_0.20-45    pkgconfig_2.0.3   
[15] png_0.1-8          rlang_1.1.1        cli_3.6.1          rstudioapi_0.14    fastmap_1.1.1      stringr_1.5.0      withr_2.5.0       
[22] dplyr_1.1.2        generics_0.1.3     vctrs_0.6.2        rprojroot_2.0.3    cowplot_1.1.1      grid_4.1.2         tidyselect_1.2.0  
[29] here_1.0.1         glue_1.6.2         R6_2.5.1           dtw_1.23-1         fansi_1.0.4        readxl_1.4.1       cellAlign_0.1.0   
[36] pheatmap_1.0.12    purrr_1.0.1        tidyr_1.3.0        ggplot2_3.4.2      reshape2_1.4.4     magrittr_2.0.3     scales_1.2.1      
[43] colorspace_2.1-0   utf8_1.2.3         stringi_1.7.12     proxy_0.4-27       munsell_0.5.0      cachem_1.0.8
